### ISSUE TITLE
Cheat simply doesn't work

### ISSUE THREAD

**Issue by Kpoop123** [roast247/SotHax#1]
After activating the cheat and saving my settings it gives this error.

https://ibb.co/B2WmLfc

**Comment by roast247** [comment]
I updated it, it should be working now, new file was uploaded

**Comment by Naeem25th** [comment]
Still the same error

**Comment by roast247** [comment]
It works for a lot of other people, not too sure why it isn't working for you

**Comment by roast247** [comment]
Should actually work now with latest file
