### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by cringelorde** [roast247/SotHax#6]
always getting a microsoft .net framework error. How can I fix that? Also, when I download the source code, it's just downloading the same release! What the hell?!

**Comment by roast247** [comment]
doesn't help when you don't give me the .NET error code. Also, If you would actually read. I said I am not releasing the source code till the next "big" update or until someone gets banned, which probably won't happen.

**Comment by roast247** [comment]
I updated the files

**Comment by roast247** [comment]
make sure you actually have the game opened before you start it as well
