### ISSUE TITLE
here u go, an error text log.

### ISSUE THREAD

**Issue by cringelorde** [roast247/SotHax#8]
Also, with the new update (5 hours ago) my antivirus started saying that this is a virus. It didn't happen with older version, not working even with turned off antivirus and google security.

**Comment by cringelorde** [comment]
Also, there is a broken readme.md
I think github will ban u if u wouldn't fix it, not really sure brotha

**Comment by roast247** [comment]
Not too sure why Antivirus is being a factor in here, thats odd. The readme.md is not broken, don't know what you are talking about
