### ISSUE TITLE
Framework error

### ISSUE THREAD

**Issue by CHRIZZ83** [roast247/SotHax#9]
Every time I go to save settings it's gives me an error saying the request was aborted: Could not create SSL/TLS secure channel.

![fdsasdf](https://user-images.githubusercontent.com/87447656/125686952-8af65a04-0130-4af4-acab-e39013e834ad.PNG)

**Comment by CHRIZZ83** [comment]
Also have the latest .Net framework.

**Comment by Naeem25th** [comment]
Same

**Comment by CHRIZZ83** [comment]
Your bio says "Have a question? I'll answer it asap!" but that's pretty false. Thanks for helping lol.

**Comment by roast247** [comment]
try the newest file
